#!/usr/bin/bash

sudo apt update
sudo apt upgrade
sudo apt autoremove

while :
	do
		read -p "Do you want to refresh snaps? [Y/n]: " answer
		answer="$answer" | awk '{print tolower($0)}'

		case $answer in
			n|no)
				break;;
			y|yes|"")
				sudo snap refresh;;
			*)
				echo "Please, provide a valid answer (yes/no).";;
		esac
	done

# if [[ "$(pwd)/fastupdate" =~ $PATH ]]; then
# 	exit 0
# fi
# 
# while :
# 	do
# 		read -p "This script isn't in your PATH. Do you want that to add to it from the current file location? [y/n]: " answer
# 		answer="$answer" | awk '{print tolower($0)}'
# 
# 		case $answer in
# 			n|no)
# 				exit 0;;
# 			y|yes)
# 				break;;
# 			*)
# 				echo "Please, provide a valid answer (yes/no).";;
# 		esac
# 	done
# 
# 	echo "PATH=$PATH:$(pwd)/fastupdate" >> $HOME/.bashrc
# 	echo "export PATH"
# 	source $HOME/.bashrc
