#!/usr/bin/bash

set -e

sudo apt update
sudo apt upgrade
sudo apt autoremove

while :
	do
		read -rp "Do you want to refresh snaps? [Y/n]: " answer
		answer="$answer" | awk '{print tolower($0)}'

		case "$answer" in
			n|no)
				break;;
			y|yes|"")
				sudo snap refresh
				break;;
			*)
				echo "Please, provide a valid answer (yes/no).";;
		esac
	done
